### ISSUE TITLE
Set up development database separate from production database

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/aggregator#20]
moved from https://github.com/cybergreen-net/stats-new/issues/24

**Comment by zelima** [comment]
Variables are moved from main script and they are configurable from .env.json
Next step would be to set up databases

**Comment by aaronkaplan** [comment]
Please don't forget to document the dev/prod setup (when to use what and how to use it and how to switch between dev to prod and vice versa). Thanks!

**Comment by zelima** [comment]
Databases dev and prod are set up (manually for now) in both Redshift and RDS. Currently live website is populated from RDS prod db. 
README updated on how to switch between dev and prod stages with changing only one variable in .env.json
Next step would be automate set up and teardown process.

**Comment by zelima** [comment]
Databases dev and prod are set up (manually for now) in both Redshift and RDS. Currently live website is populated from RDS prod db. 
README updated on how to switch between dev and prod stages with changing only one variable in .env.json
Next step would be automate set up and teardown process.

**Comment by zelima** [comment]
Databases dev and prod are set up (manually for now) in both Redshift and RDS. Currently live website is populated from RDS prod db. 
README updated on how to switch between dev and prod stages with changing only one variable in .env.json
Next step would be automate set up and teardown process.

**Comment by zelima** [comment]
Databases dev and prod are set up (manually for now) in both Redshift and RDS. Currently live website is populated from RDS prod db. 
README updated on how to switch between dev and prod stages with changing only one variable in .env.json
Next step would be automate set up and teardown process.

**Comment by zelima** [comment]
Databases dev and prod are set up (manually for now) in both Redshift and RDS. Currently live website is populated from RDS prod db. 
README updated on how to switch between dev and prod stages with changing only one variable in .env.json
Next step would be automate set up and teardown process.
