### ISSUE TITLE
[super] Metrics (v2.0, v2.1) implementation

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/aggregator#22]
The CyberGreen Index is a number per observed entity, be that entity a country, an AS, or some other entity we can and do identify. It is a weighted sum in an ordinary way: 
`CGi = rank( j=4 j=1 Σ counti, j * weight j )`
- The rank is a declining value such that CGi = 1 is the highest value and the worst risk. 
- There are various choices of weights:
  - v2.0 simple counts weight j = 1 \/— j 
  - v2.1 amplification factor weight j = AF j 
    - Amplification factor as defined by https://www.us-cert.gov/ncas/alerts/TA14-017A 
  - v3.x densities, etc. TBD

**Comment by rgrp** [comment]
@zelima is this now DUPLICATE of #25 - if so should we close as duplicate in favour of that?

**Comment by zelima** [comment]
@rgrp yes, this is will be fixed as issues from #25 are done. 
Closing as DUPLICATE
