### ISSUE TITLE
Files on S3 should have .csv extension

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/aggregator#4]
Public files on S3 currently have no extension.

**Comment by zelima** [comment]
Seems redshift's UNLOAD do not support adding extensions at the end of the file. (It is numerating them and adding eg. 000 at the end). I guess we have to download locally and upload on s3 after, if we want them to have .csv at the end.

**Comment by rgrp** [comment]
This is tough to fix right now given how Redshift works. We could maybe fix with download and upload but that's a bit of a pain. May be look further into redshift.

**Comment by rgrp** [comment]
One option would be to do an s3 copy command after the unload and then delete original files.

http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.bucket.Bucket.copy_key

**Comment by zelima** [comment]
Fixed, files have .csv extentions http://bits.cybergreen.net/

**Comment by rgrp** [comment]
@zelima how did we fix this?

**Comment by zelima** [comment]
Using Boto3 copy command https://github.com/cybergreen-net/aggregator/blob/master/main.py#L239
